# Generated by Django 3.1.6 on 2021-04-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='Measurement',
        ),
    ]
