# Generated by Django 3.1.7 on 2021-04-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='forum_post',
            new_name='detail',
        ),
    ]
