# Generated by Django 3.1.7 on 2021-04-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210418_1637'),
        ('forum', '0002_comment'),
    ]

    operations = [
    ]
