# Generated by Django 3.1.6 on 2021-04-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='248 McCormick Rd, Charlottesville, VA 22904', max_length=200),
            preserve_default=False,
        ),
    ]
