# Generated by Django 3.1.6 on 2021-05-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(default="85 Engineer's Way, Charlottesville, VA 22903", max_length=200),
        ),
    ]
