# Generated by Django 3.1.6 on 2021-05-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_event_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default="85 Engineer's Way, Charlottesville, VA 22903", max_length=200),
        ),
    ]
