# Generated by Django 3.1.6 on 2021-05-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210503_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default='1826 University Ave, Charlottesville', max_length=200),
        ),
    ]
