# Generated by Django 3.1.6 on 2021-05-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunitySchedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='address',
            field=models.CharField(default='1826 University Ave, Charlottesville', max_length=200),
        ),
    ]
